# 📦 Import Libraries

In [1]:
import pandas as pd
import numpy as np

## 📂 Load Dataset

In [2]:
df = pd.read_csv(r"C:\Users\nosar\visual project\data\Global_Education.csv", encoding="latin-1")

## 🔍 Data Exploration

In [3]:
print(df.columns)
print('---------------------------------------------------------------------------------------------')
print(df.shape)
print('---------------------------------------------------------------------------------------------')
print(df.info())

Index(['Countries and areas', 'Latitude ', 'Longitude',
       'OOSR_Pre0Primary_Age_Male', 'OOSR_Pre0Primary_Age_Female',
       'OOSR_Primary_Age_Male', 'OOSR_Primary_Age_Female',
       'OOSR_Lower_Secondary_Age_Male', 'OOSR_Lower_Secondary_Age_Female',
       'OOSR_Upper_Secondary_Age_Male', 'OOSR_Upper_Secondary_Age_Female',
       'Completion_Rate_Primary_Male', 'Completion_Rate_Primary_Female',
       'Completion_Rate_Lower_Secondary_Male',
       'Completion_Rate_Lower_Secondary_Female',
       'Completion_Rate_Upper_Secondary_Male',
       'Completion_Rate_Upper_Secondary_Female',
       'Grade_2_3_Proficiency_Reading', 'Grade_2_3_Proficiency_Math',
       'Primary_End_Proficiency_Reading', 'Primary_End_Proficiency_Math',
       'Lower_Secondary_End_Proficiency_Reading',
       'Lower_Secondary_End_Proficiency_Math',
       'Youth_15_24_Literacy_Rate_Male', 'Youth_15_24_Literacy_Rate_Female',
       'Birth_Rate', 'Gross_Primary_Education_Enrollment',
       'Gross_Tertiary_Education_Enrollment', 'Unemployment_Rate'],
      dtype='object')
---------------------------------------------------------------------------------------------
(202, 29)
---------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 29 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Countries and areas                      202 non-null    object
 1   Latitude                                 202 non-null    float64
 2   Longitude                                202 non-null    float64
 3   OOSR_Pre0Primary_Age_Male                202 non-null    int64
 4   OOSR_Pre0Primary_Age_Female              202 non-null    int64
 5   OOSR_Primary_Age_Male                    202 non-null    int64
 6   OOSR_Primary_Age_Female                  202 non-null    int64
 7   OOSR_Lower_Secondary_Age_Male            202 non-null    int64
 8   OOSR_Lower_Secondary_Age_Female          202 non-null    int64
 9   OOSR_Upper_Secondary_Age_Male            202 non-null    int64
 10  OOSR_Upper_Secondary_Age_Female          202 non-null    int64
 11  Completion_Rate_Primary_Male             202 non-null    int64
 12  Completion_Rate_Primary_Female           202 non-null    int64
 13  Completion_Rate_Lower_Secondary_Male     202 non-null    int64
 14  Completion_Rate_Lower_Secondary_Female   202 non-null    int64
 15  Completion_Rate_Upper_Secondary_Male     202 non-null    int64
 16  Completion_Rate_Upper_Secondary_Female   202 non-null    int64
 17  Grade_2_3_Proficiency_Reading            202 non-null    int64
 18  Grade_2_3_Proficiency_Math               202 non-null    int64
 19  Primary_End_Proficiency_Reading          202 non-null    int64
 20  Primary_End_Proficiency_Math             202 non-null    int64
 21  Lower_Secondary_End_Proficiency_Reading  202 non-null    int64
 22  Lower_Secondary_End_Proficiency_Math     202 non-null    int64
 23  Youth_15_24_Literacy_Rate_Male           202 non-null    int64
 24  Youth_15_24_Literacy_Rate_Female         202 non-null    int64
 25  Birth_Rate                               202 non-null    float64
 26  Gross_Primary_Education_Enrollment       202 non-null    float64
 27  Gross_Tertiary_Education_Enrollment      202 non-null    float64
 28  Unemployment_Rate                        202 non-null    float64
dtypes: float64(6), int64(22), object(1)
memory usage: 45.9+ KB
None

## 🧹 Clean Column Names

To make column names consistent and easier to work with, we apply the following transformations:

- Remove extra spaces  
- Convert all names to lowercase  
- Replace spaces with underscores `_`

In [4]:
df.columns = (
    df.columns
    .str.strip()              
    .str.lower()              
    .str.replace(" ", "_")    
)

In [5]:
print(df.columns)
print('---------------------------------------------------------------------------------------------')
print(df.shape)

Index(['countries_and_areas', 'latitude', 'longitude',
       'oosr_pre0primary_age_male', 'oosr_pre0primary_age_female',
       'oosr_primary_age_male', 'oosr_primary_age_female',
       'oosr_lower_secondary_age_male', 'oosr_lower_secondary_age_female',
       'oosr_upper_secondary_age_male', 'oosr_upper_secondary_age_female',
       'completion_rate_primary_male', 'completion_rate_primary_female',
       'completion_rate_lower_secondary_male',
       'completion_rate_lower_secondary_female',
       'completion_rate_upper_secondary_male',
       'completion_rate_upper_secondary_female',
       'grade_2_3_proficiency_reading', 'grade_2_3_proficiency_math',
       'primary_end_proficiency_reading', 'primary_end_proficiency_math',
       'lower_secondary_end_proficiency_reading',
       'lower_secondary_end_proficiency_math',
       'youth_15_24_literacy_rate_male', 'youth_15_24_literacy_rate_female',
       'birth_rate', 'gross_primary_education_enrollment',
       'gross_tertiary_education_enrollment', 'unemployment_rate'],
      dtype='object')
---------------------------------------------------------------------------------------------
(202, 29)

## 🏷️ Rename Columns

To simplify column names and improve readability, we rename long and complex column names into shorter, more intuitive ones.

In [6]:
df = df.rename(columns={

    "countries_and_areas": "country",

    "youth_15_24_literacy_rate_male": "literacy_male",
    "youth_15_24_literacy_rate_female": "literacy_female",

    "gross_primary_education_enrollment": "primary_enrollment",
    "gross_tertiary_education_enrollment": "tertiary_enrollment",

    "primary_end_proficiency_reading": "reading_prof",
    "primary_end_proficiency_math": "math_prof",

    "completion_rate_primary_male": "comp_primary_male",
    "completion_rate_primary_female": "comp_primary_female",

    "completion_rate_lower_secondary_male": "comp_lower_male",
    "completion_rate_lower_secondary_female": "comp_lower_female",

    "completion_rate_upper_secondary_male": "comp_upper_male",
    "completion_rate_upper_secondary_female": "comp_upper_female",

    "oosr_pre0primary_age_male": "oosr_pre_male",
    "oosr_pre0primary_age_female": "oosr_pre_female",

    "oosr_primary_age_male": "oosr_primary_male",
    "oosr_primary_age_female": "oosr_primary_female",

    "oosr_lower_secondary_age_male": "oosr_lower_male",
    "oosr_lower_secondary_age_female": "oosr_lower_female",

    "oosr_upper_secondary_age_male": "oosr_upper_male",
    "oosr_upper_secondary_age_female": "oosr_upper_female",

    "grade_2_3_proficiency_reading": "g2_reading",
    "grade_2_3_proficiency_math": "g2_math",

    "lower_secondary_end_proficiency_reading": "lower_reading",
    "lower_secondary_end_proficiency_math": "lower_math"
})

In [7]:
print(df.columns)
print('---------------------------------------------------------------------------------------------')
print(df.shape)

Index(['country', 'latitude', 'longitude', 'oosr_pre_male', 'oosr_pre_female',
       'oosr_primary_male', 'oosr_primary_female', 'oosr_lower_male',
       'oosr_lower_female', 'oosr_upper_male', 'oosr_upper_female',
       'comp_primary_male', 'comp_primary_female', 'comp_lower_male',
       'comp_lower_female', 'comp_upper_male', 'comp_upper_female',
       'g2_reading', 'g2_math', 'reading_prof', 'math_prof', 'lower_reading',
       'lower_math', 'literacy_male', 'literacy_female', 'birth_rate',
       'primary_enrollment', 'tertiary_enrollment', 'unemployment_rate'],
      dtype='object')
---------------------------------------------------------------------------------------------
(202, 29)

In [8]:
df.head()

,country,latitude,longitude,oosr_pre_male,oosr_pre_female,oosr_primary_male,oosr_primary_female,oosr_lower_male,oosr_lower_female,oosr_upper_male,...,reading_prof,math_prof,lower_reading,lower_math,literacy_male,literacy_female,birth_rate,primary_enrollment,tertiary_enrollment,unemployment_rate
0,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,44,...,13,11,0,0,74,56,32.49,104.0,9.7,11.12
1,Albania,41.153332,20.168331,4,2,6,3,6,1,21,...,0,0,48,58,99,100,11.78,107.0,55.0,12.33
2,Algeria,28.033886,1.659626,0,0,0,0,0,0,0,...,0,0,21,19,98,97,24.28,109.9,51.4,11.70
3,Andorra,42.506285,1.521801,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7.20,106.4,0.0,0.00
4,Angola,11.202692,17.873887,31,39,0,0,0,0,0,...,0,0,0,0,0,0,40.73,113.5,9.3,6.89

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              202 non-null    object
 1   latitude             202 non-null    float64
 2   longitude            202 non-null    float64
 3   oosr_pre_male        202 non-null    int64
 4   oosr_pre_female      202 non-null    int64
 5   oosr_primary_male    202 non-null    int64
 6   oosr_primary_female  202 non-null    int64
 7   oosr_lower_male      202 non-null    int64
 8   oosr_lower_female    202 non-null    int64
 9   oosr_upper_male      202 non-null    int64
 10  oosr_upper_female    202 non-null    int64
 11  comp_primary_male    202 non-null    int64
 12  comp_primary_female  202 non-null    int64
 13  comp_lower_male      202 non-null    int64
 14  comp_lower_female    202 non-null    int64
 15  comp_upper_male      202 non-null    int64
 16  comp_upper_female    202 non-null    int64
 17  g2_reading           202 non-null    int64
 18  g2_math              202 non-null    int64
 19  reading_prof         202 non-null    int64
 20  math_prof            202 non-null    int64
 21  lower_reading        202 non-null    int64
 22  lower_math           202 non-null    int64
 23  literacy_male        202 non-null    int64
 24  literacy_female      202 non-null    int64
 25  birth_rate           202 non-null    float64
 26  primary_enrollment   202 non-null    float64
 27  tertiary_enrollment  202 non-null    float64
 28  unemployment_rate    202 non-null    float64
dtypes: float64(6), int64(22), object(1)
memory usage: 45.9+ KB
None

## 🔍 Detect Invalid Zero Values

In [10]:
for col in ["literacy_male", "literacy_female", "reading_prof", "math_prof"]:
    print(col)
    print((df[col] == 0).sum())
    print("------")

literacy_male
123
------
literacy_female
123
------
reading_prof
158
------
math_prof
153
------

In [11]:
import numpy as np

cols = ["literacy_male", "literacy_female", "reading_prof", "math_prof"]

for col in cols:
    df[col] = df[col].replace(0, np.nan)

In [12]:
print(df[cols].isnull().sum())

literacy_male      123
literacy_female    123
reading_prof       158
math_prof          153
dtype: int64

In [13]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [14]:
print(df[cols].isnull().sum())

literacy_male      0
literacy_female    0
reading_prof       0
math_prof          0
dtype: int64

## 🧠 Feature Engineering

We create new features to better analyze education levels across countries.

### 📊 Literacy Rate
This represents the average literacy rate between males and females.

### ⚖️ Literacy Gap
This shows the difference between male and female literacy rates, helping identify gender inequality in education.

In [15]:
df["literacy_rate"] = (df["literacy_male"] + df["literacy_female"]) / 2
df["literacy_gap"] = df["literacy_male"] - df["literacy_female"]

In [16]:
print(df[["literacy_male", "literacy_female", "literacy_rate", "literacy_gap"]].head())

   literacy_male  literacy_female  literacy_rate  literacy_gap
0      74.000000        56.000000      65.000000     18.000000
1      99.000000       100.000000      99.500000     -1.000000
2      98.000000        97.000000      97.500000      1.000000
3      91.544304        89.708861      90.626582      1.835443
4      91.544304        89.708861      90.626582      1.835443

In [17]:
df["literacy_rate"] = df["literacy_rate"].round(2)
df["literacy_gap"] = df["literacy_gap"].round(2)

In [18]:
print(df[["literacy_male", "literacy_female", "literacy_rate", "literacy_gap"]].head())

   literacy_male  literacy_female  literacy_rate  literacy_gap
0      74.000000        56.000000          65.00         18.00
1      99.000000       100.000000          99.50         -1.00
2      98.000000        97.000000          97.50          1.00
3      91.544304        89.708861          90.63          1.84
4      91.544304        89.708861          90.63          1.84

In [19]:
print(df.describe())

         latitude   longitude  oosr_pre_male  oosr_pre_female  \
count  202.000000  202.000000     202.000000       202.000000
mean    25.081422   55.166928      19.658416        19.282178
std     16.813639   45.976287      25.007604        25.171147
min      0.023559    0.824782       0.000000         0.000000
25%     11.685062   18.665678       0.000000         0.000000
50%     21.207861   43.518091       9.000000         7.000000
75%     39.901792   77.684945      31.000000        30.000000
max     64.963051  178.065032      96.000000        96.000000

       oosr_primary_male  oosr_primary_female  oosr_lower_male  \
count         202.000000           202.000000       202.000000
mean            5.282178             5.569307         8.707921
std             9.396442            10.383092        13.258203
min             0.000000             0.000000         0.000000
25%             0.000000             0.000000         0.000000
50%             1.000000             1.000000         2.000000
75%             6.000000             6.750000        12.750000
max            58.000000            67.000000        61.000000

       oosr_lower_female  oosr_upper_male  oosr_upper_female  ...  \
count         202.000000       202.000000         202.000000  ...
mean            8.831683        20.292079          19.975248  ...
std            14.724717        21.485592          23.140376  ...
min             0.000000         0.000000           0.000000  ...
25%             0.000000         0.250000           0.250000  ...
50%             2.000000        15.000000          12.000000  ...
75%            10.750000        32.750000          30.000000  ...
max            70.000000        84.000000          89.000000  ...

       lower_reading  lower_math  literacy_male  literacy_female  birth_rate  \
count     202.000000  202.000000     202.000000       202.000000  202.000000
mean       25.787129   24.450495      91.544304        89.708861   18.914010
std        33.181384   31.965467       8.236430        11.024239   10.828184
min         0.000000    0.000000      48.000000        29.000000    0.000000
25%         0.000000    0.000000      91.544304        89.708861   10.355000
50%         0.000000    0.000000      91.544304        89.708861   17.550000
75%        56.750000   50.750000      94.000000        96.750000   27.692500
max        89.000000   94.000000     100.000000       100.000000   46.080000

       primary_enrollment  tertiary_enrollment  unemployment_rate  \
count          202.000000           202.000000         202.000000
mean            94.942574            34.392574           6.000000
std             29.769338            29.978206           5.273136
min              0.000000             0.000000           0.000000
25%             97.200000             9.000000           2.302500
50%            101.850000            24.850000           4.585000
75%            107.300000            59.975000           8.655000
max            142.500000           136.600000          28.180000

       literacy_rate  literacy_gap
count     202.000000    202.000000
mean       90.628663      1.838218
std         9.567444      3.549831
min        38.500000     -5.000000
25%        90.630000      0.000000
50%        90.630000      1.840000
75%        95.375000      1.840000
max       100.000000     27.000000

[8 rows x 30 columns]

In [20]:
print(df[df["literacy_rate"] > 100])
print(df[df["literacy_rate"] < 0])

Empty DataFrame
Columns: [country, latitude, longitude, oosr_pre_male, oosr_pre_female, oosr_primary_male, oosr_primary_female, oosr_lower_male, oosr_lower_female, oosr_upper_male, oosr_upper_female, comp_primary_male, comp_primary_female, comp_lower_male, comp_lower_female, comp_upper_male, comp_upper_female, g2_reading, g2_math, reading_prof, math_prof, lower_reading, lower_math, literacy_male, literacy_female, birth_rate, primary_enrollment, tertiary_enrollment, unemployment_rate, literacy_rate, literacy_gap]
Index: []

[0 rows x 31 columns]
Empty DataFrame
Columns: [country, latitude, longitude, oosr_pre_male, oosr_pre_female, oosr_primary_male, oosr_primary_female, oosr_lower_male, oosr_lower_female, oosr_upper_male, oosr_upper_female, comp_primary_male, comp_primary_female, comp_lower_male, comp_lower_female, comp_upper_male, comp_upper_female, g2_reading, g2_math, reading_prof, math_prof, lower_reading, lower_math, literacy_male, literacy_female, birth_rate, primary_enrollment, tertiary_enrollment, unemployment_rate, literacy_rate, literacy_gap]
Index: []

[0 rows x 31 columns]

In [21]:
print(df.shape)

(202, 31)

In [22]:
print(df.isnull().sum().sum())

0

In [23]:
print(df["literacy_rate"].min(), df["literacy_rate"].max())

38.5 100.0

In [24]:
print(df.duplicated().sum())

0

## 💾 Save Cleaned Dataset

In [25]:
df.to_csv(r"C:\Users\nosar\visual project\data\cleaned_education.csv", index=False)

In [31]:
df2 = pd.read_csv(r"C:\Users\nosar\visual project\data\cleaned_education.csv")

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              202 non-null    object
 1   latitude             202 non-null    float64
 2   longitude            202 non-null    float64
 3   oosr_pre_male        202 non-null    int64
 4   oosr_pre_female      202 non-null    int64
 5   oosr_primary_male    202 non-null    int64
 6   oosr_primary_female  202 non-null    int64
 7   oosr_lower_male      202 non-null    int64
 8   oosr_lower_female    202 non-null    int64
 9   oosr_upper_male      202 non-null    int64
 10  oosr_upper_female    202 non-null    int64
 11  comp_primary_male    202 non-null    int64
 12  comp_primary_female  202 non-null    int64
 13  comp_lower_male      202 non-null    int64
 14  comp_lower_female    202 non-null    int64
 15  comp_upper_male      202 non-null    int64
 16  comp_upper_female    202 non-null    int64
 17  g2_reading           202 non-null    int64
 18  g2_math              202 non-null    int64
 19  reading_prof         202 non-null    float64
 20  math_prof            202 non-null    float64
 21  lower_reading        202 non-null    int64
 22  lower_math           202 non-null    int64
 23  literacy_male        202 non-null    float64
 24  literacy_female      202 non-null    float64
 25  birth_rate           202 non-null    float64
 26  primary_enrollment   202 non-null    float64
 27  tertiary_enrollment  202 non-null    float64
 28  unemployment_rate    202 non-null    float64
 29  literacy_rate        202 non-null    float64
 30  literacy_gap         202 non-null    float64
dtypes: float64(12), int64(18), object(1)
memory usage: 49.1+ KB

In [33]:
df2.head().T

                               0          1          2          3          4
country              Afghanistan    Albania    Algeria    Andorra     Angola
latitude                33.93911  41.153332  28.033886  42.506285  11.202692
longitude              67.709953  20.168331   1.659626   1.521801  17.873887
oosr_pre_male                  0          4          0          0         31
oosr_pre_female                0          2          0          0         39
oosr_primary_male              0          6          0          0          0
oosr_primary_female            0          3          0          0          0
oosr_lower_male                0          6          0          0          0
oosr_lower_female              0          1          0          0          0
oosr_upper_male               44         21          0          0          0
oosr_upper_female             69         15          0          0          0
comp_primary_male             67         94         93          0         63
comp_primary_female           40         96         93          0         57
comp_lower_male               49         98         49          0         42
comp_lower_female             26         97         65          0         32
comp_upper_male               32         76         22          0         24
comp_upper_female             14         80         37          0         15
g2_reading                    22          0          0          0          0
g2_math                       25          0          0          0          0
reading_prof                13.0  49.204545  49.204545  49.204545  49.204545
math_prof                   11.0   42.77551   42.77551   42.77551   42.77551
lower_reading                  0         48         21          0          0
lower_math                     0         58         19          0          0
literacy_male               74.0       99.0       98.0  91.544304  91.544304
literacy_female             56.0      100.0       97.0  89.708861  89.708861
birth_rate                 32.49      11.78      24.28        7.2      40.73
primary_enrollment         104.0      107.0      109.9      106.4      113.5
tertiary_enrollment          9.7       55.0       51.4        0.0        9.3
unemployment_rate          11.12      12.33       11.7        0.0       6.89
literacy_rate               65.0       99.5       97.5      90.63      90.63
literacy_gap                18.0       -1.0        1.0       1.84       1.84

In [18]:
literacy_raw = pd.read_csv(
    r"C:\Users\nosar\p)visual project\data\API_SE.ADT.LITR.ZS_DS2_en_csv_v2.csv",
    skiprows=4
)

unemp_raw = pd.read_csv(
    r"C:\Users\nosar\p)visual project\data\API_SL.UEM.TOTL.ZS_DS2_en_csv_v2.csv",
    skiprows=4
)

In [19]:
literacy = literacy_raw.iloc[4:]
unemp = unemp_raw.iloc[4:]

In [20]:
years = [str(y) for y in range(2015, 2021)]

literacy = literacy[["Country Name"] + years]
unemp = unemp[["Country Name"] + years]

In [21]:
literacy = literacy.melt(
    id_vars=["Country Name"],
    var_name="year",
    value_name="literacy_rate"
)

unemp = unemp.melt(
    id_vars=["Country Name"],
    var_name="year",
    value_name="unemployment_rate"
)

In [22]:
literacy.columns = ["country", "year", "literacy_rate"]
unemp.columns = ["country", "year", "unemployment_rate"]

In [23]:
# توحيد اسم الدولة
literacy["country"] = literacy["country"].str.strip().str.lower()
unemp["country"] = unemp["country"].str.strip().str.lower()

# تحويل types
literacy["year"] = literacy["year"].astype(int)
unemp["year"] = unemp["year"].astype(int)

literacy["literacy_rate"] = pd.to_numeric(literacy["literacy_rate"], errors="coerce")
unemp["unemployment_rate"] = pd.to_numeric(unemp["unemployment_rate"], errors="coerce")

In [24]:
literacy = literacy.dropna(subset=["literacy_rate"])
unemp = unemp.dropna(subset=["unemployment_rate"])

In [25]:
df_final = literacy.merge(
    unemp,
    on=["country", "year"],
    how="inner"
)

In [27]:
edu = pd.read_csv(r"C:\Users\nosar\p)visual project\data\cleaned_education.csv")

edu["country"] = edu["country"].str.strip().str.lower()

df_final = df_final[df_final["country"].isin(edu["country"])]

In [28]:
df_final.to_csv("time_series.csv", index=False)